Repository cassandra/home-information, pull requests merged in 2025-02, with the labels that each got.

#10 Added refs to pip install and migrate per docs ssue #5.
  docs/dev/Workflow.md
Labels: documentation

#11 Changed install docs to go to releases.
  README.md
  docs/Installation.md
  docs/dev/Setup.md
Labels: documentation

#20 Fixed Makefile and Dockerfile to ensure execute permissions.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/operations.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/tests.md
  Dockerfile
  Makefile
Labels: bug, ops

#24 Added code of conduct page, moved content there, added links.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#36 Ensure service container restarts on reboot
  .github/PULL_REQUEST_TEMPLATE.md
  deploy/run_container.sh
  docs/Installation.md
  docs/dev/ReleaseProcesses.md
Labels: ops
